import test from 'node:test';import assert from 'node:assert/strict';import {audioStatistics} from '../src/experimental/audio-statistics.js';import {validateMixAnalysis,currentMixAnalysis} from '../src/experimental/mix-analysis.js';import {SessionHistory,newSession} from '../src/experimental/session.js';import {planDawEdit} from '../server/daw-agent.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
const fixture=()=>{const s=new SessionHistory(newSession()).session;return {s,a:{sessionId:s.id,revision:s.revision,measuredAt:Date.now(),sampleRate:48000,frames:48000,channels:audioStatistics([new Float32Array(48000),new Float32Array(48000)])}};};
test('full sample statistics handle silence, polarity, first peak location, RMS and above-full-scale counts',()=>{const [a,b]=audioStatistics([Float32Array.from([0,.5,-1,1,-1.5]),new Float32Array(5)]);near(a.peakDb,20*Math.log10(1.5));near(a.rmsDb,10*Math.log10(4.5/5));assert.equal(a.peakFrame,4);assert.equal(a.overSamples,1);assert.deepEqual(b,{peakDb:null,rmsDb:null,peakFrame:null,overSamples:0});const [first]=audioStatistics([Float32Array.from([-1,1]),new Float32Array(2)]);assert.equal(first.peakFrame,0);assert.equal(first.overSamples,0);});
test('statistics reject malformed audio and non-finite sample values',()=>{for(const input of [[],[new Float32Array(1)],[new Float32Array(),new Float32Array()],[new Float32Array(1),new Float32Array(2)],[Float32Array.from([NaN]),new Float32Array(1)],[Float32Array.from([Infinity]),new Float32Array(1)]])assert.throws(()=>audioStatistics(input));});
test('analysis is tied to exact document revision and rendered frame count, with consistent channel measurements',()=>{const {s,a}=fixture();assert.deepEqual(validateMixAnalysis(a,s),a);assert.equal(currentMixAnalysis(a,{...s,revision:s.revision+1}),undefined);assert.equal(currentMixAnalysis(a,{...s,id:'other'}),undefined);for(const patch of [{frames:47999},{measuredAt:Date.now()+10000},{channels:[{peakDb:-6,rmsDb:0,peakFrame:1,overSamples:0},a.channels[1]]},{channels:[{peakDb:1,rmsDb:-2,peakFrame:1,overSamples:0},a.channels[1]]},{channels:[{peakDb:null,rmsDb:null,peakFrame:1,overSamples:0},a.channels[1]]},{channels:[{peakDb:0,rmsDb:0,peakFrame:48000,overSamples:0},a.channels[1]]}])assert.throws(()=>validateMixAnalysis({...a,...patch},s));assert.ok(validateMixAnalysis({...a,measuredAt:Date.now()-3600000},s));});
test('agent receives current full-mix measurements and rejects stale results before invoking a provider',async()=>{const {s,a}=fixture();let sent,calls=0;const options={key:'test',model:'test',fetchImpl:async(_,request)=>{calls++;sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[{type:'message',content:[{type:'output_text',text:'The rendered mix is silent.'}]}]})};}};const result=await planDawEdit({session:s,instruction:'What is the peak?',mixAnalysis:a},options);assert.deepEqual(JSON.parse(sent.input.at(-1).content).mixAnalysis,a);assert.deepEqual(result.commands,[]);assert.equal(sent.store,false);await assert.rejects(planDawEdit({session:s,instruction:'Measure',mixAnalysis:{...a,revision:999}},options),/does not match/);assert.equal(calls,1);});
test('agent can request a bounded browser analysis only when available and current measurements are missing',async()=>{
 const {s,a}=fixture();let sent;const reply=(calls)=>({key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:calls})};}}),call={type:'function_call',name:'analyze_mix',arguments:'{}'};
 const result=await planDawEdit({session:s,instruction:'Measure the mix',allowAnalysis:true},reply([call]));assert.equal(result.action,'analyze_mix');assert.equal(result.revision,s.revision);assert.deepEqual(result.commands,[]);assert.ok(sent.tools.some(t=>t.name==='analyze_mix'));assert.equal(sent.parallel_tool_calls,false);
 for(const input of [{allowAnalysis:false},{allowAnalysis:true,mixAnalysis:a}]){await assert.rejects(planDawEdit({session:s,instruction:'Measure',...input},reply([call])),/Unexpected/);assert.ok(!sent.tools.some(t=>t.name==='analyze_mix'));}
 await assert.rejects(planDawEdit({session:s,instruction:'Measure',allowAnalysis:true},reply([{...call,arguments:'{"commands":[]}'}])));
 await assert.rejects(planDawEdit({session:s,instruction:'Measure',allowAnalysis:true},reply([call,{type:'function_call',name:'edit_session',arguments:'{}'}])),/Unexpected/);
});
test('model edit plans can request post-edit verification with a boolean flag',async()=>{
 const {s}=fixture();let sent;const options=value=>({key:'test',model:'test',fetchImpl:async(_,request)=>{sent=JSON.parse(request.body);return {ok:true,json:async()=>({output:[{type:'function_call',name:'edit_session',arguments:JSON.stringify({summary:'Adjusted master gain; verification follows.',commands:[{op:'master.gain.offset',values:{deltaDb:-3}}],verifyMix:value})}]})};}});
 const plan=await planDawEdit({session:s,instruction:'Reduce and verify'},options(true));assert.equal(plan.verifyMix,true);assert.equal(plan.commands[0].values.deltaDb,-3);assert.equal(sent.tools.find(t=>t.name==='edit_session').parameters.properties.verifyMix.type,'boolean');await assert.rejects(planDawEdit({session:s,instruction:'Reduce and verify'},options('true')));
});
