import test from 'node:test';import assert from 'node:assert/strict';
import {newSession,applyCommands,SessionHistory} from '../src/experimental/session.js';
import {automationValue,effectTail} from '../src/experimental/effects.js';
const base=()=>applyCommands(newSession(),[{op:'track.add',values:{id:'track'}}]);
test('effect chains validate settings, bypass and reorder through the shared command harness',()=>{const s=applyCommands(base(),[{op:'effect.add',target:'track',values:{id:'eq',kind:'eq',type:'highpass',frequency:100}},{op:'effect.add',target:'track',values:{id:'echo',kind:'delay',time:.2}},{op:'effect.move',target:'echo',values:{index:0}},{op:'effect.set',target:'eq',values:{enabled:false}}]);assert.equal(s.tracks[0].effects[0].id,'echo');assert.equal(s.tracks[0].effects[1].enabled,false);const history=new SessionHistory(s);assert.throws(()=>history.execute([{op:'effect.set',target:'echo',values:{mix:.5}},{op:'effect.set',target:'echo',values:{feedback:1}}]));assert.deepEqual(history.session,s);assert.throws(()=>applyCommands(s,[{op:'effect.set',target:'eq',values:{kind:'delay'}}]));assert.throws(()=>applyCommands(s,[{op:'effect.add',target:'track',values:{kind:'eq',frequency:0}}]));});
test('automation upserts timestamps, interpolates, bounds values and survives undo',()=>{const s=applyCommands(base(),[{op:'automation.point',target:'track',values:{id:'a',parameter:'gainDb',time:0,value:-12}},{op:'automation.point',target:'track',values:{id:'b',parameter:'gainDb',time:4,value:0}},{op:'automation.point',target:'track',values:{parameter:'gainDb',time:4,value:-4}}]);const points=s.tracks[0].automation;assert.equal(points.length,2);assert.equal(automationValue(points,'gainDb',2,0),-8);assert.equal(automationValue(points,'gainDb',5,0),-4);assert.equal(automationValue(points,'pan',2,.5),.5);assert.throws(()=>applyCommands(s,[{op:'automation.point',target:'track',values:{parameter:'pan',time:0,value:2}}]));const h=new SessionHistory(s);h.execute([{op:'automation.clear',target:'track',values:{parameter:'gainDb'}}]);assert.equal(h.session.tracks[0].automation.length,0);h.undo();assert.equal(h.session.tracks[0].automation.length,2);});
test('effect tails include echo repetitions and reverberation while bypass contributes no tail',()=>{assert.equal(effectTail([{kind:'reverb',enabled:true,decay:2}]),2);assert.equal(effectTail([{kind:'reverb',enabled:false,decay:2}]),0);assert.ok(effectTail([{kind:'delay',enabled:true,time:.25,feedback:.5,mix:.5}])>2);});
test('gain utility validates polarity, width and automated gain on every chain with undo',()=>{
 const h=new SessionHistory(base());h.execute([{op:'effect.add',target:'track',values:{id:'utility',kind:'gain',invertLeft:true,swap:true,width:0}},{op:'effect.automation.point',target:'utility',values:{parameter:'gainDb',time:0,value:24}},{op:'effect.automation.point',target:'utility',values:{parameter:'width',time:1,value:2}},{op:'effect.add',target:h.session.id,values:{id:'master-gain',kind:'gain'}}]);const before=structuredClone(h.session);assert.equal(before.tracks[0].effects[0].invertRight,false);assert.equal(effectTail(before.tracks[0].effects),0);
 for(const values of [{width:3},{gainDb:25},{invertRight:1},{swap:'true'}]){assert.throws(()=>h.execute([{op:'effect.set',target:'utility',values}]));assert.deepEqual(h.session,before);}assert.throws(()=>h.execute([{op:'effect.automation.point',target:'utility',values:{parameter:'width',time:0,value:-1}}]));h.execute([{op:'effect.set',target:'utility',values:{enabled:false}}]);h.undo();assert.deepEqual(h.session.tracks,before.tracks);h.redo();assert.equal(h.session.tracks[0].effects[0].enabled,false);
});
