import test from 'node:test';
import assert from 'node:assert/strict';
import JSZip from 'jszip';
import {newSession,applyCommands} from '../src/experimental/session.js';
import {exportArchive,importArchive} from '../src/experimental/archive.js';
const fixture=()=>applyCommands(newSession(),[{op:'track.add',values:{id:'t'}},{op:'region.add',target:'t',values:{assetId:'source',duration:2}},{op:'region.add',target:'t',values:{assetId:'source',start:3,duration:2}},{op:'effect.add',target:'t',values:{kind:'delay'}}]);
test('portable archive preserves media bytes, shared references, edits and effects with isolated IDs',async()=>{const session=fixture(),file=new File([new Uint8Array([0,255,1,127])],'original.wav',{type:'audio/wav',lastModified:123});const blob=await exportArchive(session,new Map([['source',file]])),restored=await importArchive(await blob.arrayBuffer());assert.equal(restored.records.length,1);assert.deepEqual(new Uint8Array(await restored.records[0].file.arrayBuffer()),new Uint8Array(await file.arrayBuffer()));assert.equal(restored.records[0].file.name,file.name);assert.equal(restored.records[0].file.lastModified,123);assert.notEqual(restored.session.id,session.id);assert.notEqual(restored.records[0].id,'source');assert.ok(restored.session.tracks[0].regions.every(r=>r.assetId===restored.records[0].id));assert.deepEqual(restored.session.tracks[0].effects,session.tracks[0].effects);assert.equal(restored.session.tracks[0].regions[1].start,3);});
test('archive refuses missing media and invalid region invariants',async()=>{await assert.rejects(exportArchive(fixture(),new Map()),/missing/);const s=fixture();s.tracks[0].regions[0].fadeIn=10;await assert.rejects(exportArchive(s,new Map()),/Fades/);});
test('archive rejects missing entries and duplicate manifest identities',async()=>{const blob=await exportArchive(fixture(),new Map([['source',new File(['audio'],'a.wav')]]));const zip=await JSZip.loadAsync(await blob.arrayBuffer());zip.remove('media/0');await assert.rejects(importArchive(await zip.generateAsync({type:'uint8array'})),/missing/);const manifest=JSON.parse(await zip.file('project.json').async('string'));manifest.assets.push(manifest.assets[0]);zip.file('project.json',JSON.stringify(manifest));await assert.rejects(importArchive(await zip.generateAsync({type:'uint8array'})),/manifest/);});
