import {scheduleDrum} from './drums.js';
import {scheduleMidiChannel,schedulePitchBend,sustainedEnd} from './midi-events.js';
import {audibleSources,routedTail,validateRouting} from './routing.js';
import {connectEffects,scheduleAutomation} from './effects.js';
export const sessionDuration=session=>Math.max(1,...session.tracks.flatMap(t=>t.regions.map(r=>r.start+r.duration+routedTail(session,t))));
const linear=db=>10**(db/20);
function envelope(r,time){return Math.max(0,Math.min(1,r.fadeIn?time/r.fadeIn:1,r.fadeOut?(r.duration-time)/r.fadeOut:1));}
export function scheduleSession(context,session,buffers,position=0,options={}){
 validateRouting(session);const active=audibleSources(session);for(const t of active.filter(t=>t.kind==='audio'))for(const r of t.regions){const buffer=buffers.get(r.assetId);if(!buffer)throw Error(`Missing audio: ${r.name}. Re-import the file.`);if(r.offset+r.duration>buffer.duration+.01)throw Error(`Region exceeds its source: ${r.name}`);}
 const nodes=[],base=options.baseTime??context.currentTime+.025,master=context.createGain();master.gain.value=linear(session.masterDb);master.connect(context.destination);nodes.push(master);
 const channels=new Map();
 for(const track of session.tracks.filter(t=>t.kind!=='video')){const input=context.createGain(),gain=context.createGain(),pan=context.createStereoPanner();connectEffects(context,input,track.effects,nodes).connect(gain);if(track.mute)gain.gain.value=0;else scheduleAutomation(gain.gain,track.automation||[],'gainDb',position,base,track.gainDb);scheduleAutomation(pan.pan,track.automation||[],'pan',position,base,track.pan);gain.connect(pan);nodes.push(input,gain,pan);channels.set(track.id,{input,pan});}
 for(const track of session.tracks.filter(t=>t.kind!=='video')){const {pan}=channels.get(track.id);pan.connect(track.output?channels.get(track.output).input:master);for(const send of track.sends||[]){const amount=context.createGain();amount.gain.value=linear(send.gainDb);pan.connect(amount).connect(channels.get(send.busId).input);nodes.push(amount);}}
 for(const track of active){const {input}=channels.get(track.id);
  for(const r of track.regions){const relative=Math.max(0,position-r.start),length=r.duration-relative;if(length<=0)continue;const when=base+Math.max(0,r.start-position),regionGain=context.createGain(),level=linear(r.gainDb);regionGain.connect(input);nodes.push(regionGain);regionGain.gain.setValueAtTime(level*envelope(r,relative),when);for(const edge of [r.fadeIn,r.duration-r.fadeOut,r.duration].filter(t=>t>relative).sort((a,b)=>a-b))regionGain.gain.linearRampToValueAtTime(level*envelope(r,edge),when+edge-relative);
   if(track.kind==='midi'){const channels=new Map();for(const note of r.notes){const channel=note.channel||0,events=(r.events||[]).filter(e=>e.channel===channel),end=sustainedEnd(note,events,r.duration);if(!channels.has(channel))channels.set(channel,scheduleMidiChannel(context,regionGain,events,relative,when,nodes));if(track.instrument==='drumKit'){scheduleDrum(context,channels.get(channel),note,relative,when,r.duration,nodes);continue;}const localStart=note.start-relative,remaining=end-note.start+Math.min(0,localStart);if(remaining<=0||note.velocity===0)continue;const osc=context.createOscillator(),amp=context.createGain(),start=when+Math.max(0,localStart);osc.type=track.instrument;osc.frequency.value=440*2**((note.pitch-69)/12);schedulePitchBend(osc,events,Math.max(relative,note.start),start,end);amp.gain.setValueAtTime(0,start);amp.gain.linearRampToValueAtTime(note.velocity*.18,start+Math.min(.008,remaining/3));amp.gain.setValueAtTime(note.velocity*.18,start+Math.max(Math.min(.008,remaining/3),remaining-.02));amp.gain.linearRampToValueAtTime(0,start+remaining);osc.connect(amp).connect(channels.get(channel));osc.start(start);osc.stop(start+remaining);nodes.push(osc,amp);}}
   else{let buffer=buffers.get(r.assetId);if(!buffer)throw Error(`Missing audio: ${r.name}. Re-import the file.`);if(r.offset+r.duration>buffer.duration+.01)throw Error(`Region exceeds its source: ${r.name}`);let offset=r.offset+relative;if(r.reverse){const reversed=context.createBuffer(buffer.numberOfChannels,Math.ceil(r.duration*buffer.sampleRate),buffer.sampleRate);for(let c=0;c<buffer.numberOfChannels;c++){const input=buffer.getChannelData(c),output=reversed.getChannelData(c);for(let i=0;i<output.length;i++)output[i]=input[Math.floor((r.offset+r.duration)*buffer.sampleRate)-1-i]||0;}buffer=reversed;offset=relative;}const source=context.createBufferSource();source.buffer=buffer;source.connect(regionGain);source.start(when,offset,length);nodes.push(source);}
  }
 }
 return {base,stop(){for(const node of nodes){try{node.stop?.();}catch{}node.disconnect();}}};
}
export function encodeWav(buffer){const channels=buffer.numberOfChannels,frames=buffer.length,array=new ArrayBuffer(44+frames*channels*2),view=new DataView(array);const text=(offset,s)=>{for(let i=0;i<s.length;i++)view.setUint8(offset+i,s.charCodeAt(i));};text(0,'RIFF');view.setUint32(4,array.byteLength-8,true);text(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,array.byteLength-44,true);const data=Array.from({length:channels},(_,c)=>buffer.getChannelData(c));for(let i=0;i<frames;i++)for(let c=0;c<channels;c++){const n=Math.max(-1,Math.min(1,data[c][i]));view.setInt16(44+(i*channels+c)*2,Math.round(n*(n<0?32768:32767)),true);}return new Blob([array],{type:'audio/wav'});}
