import {automationValue} from './effects.js';
export function automationView(track,esc,{gainOnly=false}={}){return `<section class="daw-automation"><h4>Automation · ${esc(track.name)}</h4><label>Parameter<select data-auto-parameter><option value="gainDb">Volume (dB)</option>${gainOnly?'':'<option value="pan">Pan</option>'}</select></label><p class="muted">Click the graph to add a point. Points interpolate smoothly and override the static fader.</p><svg data-auto-graph viewBox="0 0 600 160" preserveAspectRatio="none" aria-label="Automation curve"></svg><form data-auto-form="${track.id}"><label>Time · seconds<input type="number" name="time" min="0" step=".01" value="0" required></label><label>Value<input type="number" name="value" step=".1" value="0" required></label><button type="submit">Add point</button><button type="button" data-auto-clear="${track.id}">Clear curve</button></form><div data-auto-points></div></section>`;}
export function bindAutomation(root,{track,execute,guard,duration,automationParameter='gainDb',onAutomationParameter=()=>{},
 point=values=>({op:'automation.point',target:track.id,values}),
 remove=id=>({op:'automation.delete',target:id}),
 clear=parameter=>({op:'automation.clear',target:track.id,values:{parameter}}),
}){
 if(!root)return;const parameter=root.querySelector('[data-auto-parameter]');if(!parameter)return;
 const graph=root.querySelector('[data-auto-graph]'),pointsRoot=root.querySelector('[data-auto-points]'),form=root.querySelector('[data-auto-form]');
 function draw(){const key=parameter.value,min=key==='gainDb'?-60:-1,max=key==='gainDb'?12:1,points=(track.automation||[]).filter(p=>p.parameter===key).sort((a,b)=>a.time-b.time),end=Math.max(duration,...points.map(p=>p.time));const y=value=>160-Math.min(1,Math.max(0,(value-min)/(max-min)))*160;const drawPoints=[{time:0,value:automationValue(points,key,0,track[key])},...points,{time:end,value:automationValue(points,key,end,track[key])}];graph.innerHTML=`<path d="${drawPoints.map((p,i)=>`${i?'L':'M'} ${p.time/end*600} ${y(p.value)}`).join(' ')}"/>${points.map(p=>`<circle cx="${p.time/end*600}" cy="${y(p.value)}" r="4"/>`).join('')}<text x="8" y="16">${max}${key==='gainDb'?' dB':''}</text><text x="8" y="152">${min}</text><text x="530" y="152">${end.toFixed(1)} s</text>`;pointsRoot.innerHTML=points.map(p=>`<div><span>${p.time.toFixed(2)}s · ${p.value.toFixed(2)}</span><button data-auto-remove="${p.id}" aria-label="Remove automation point at ${p.time} seconds">Remove</button></div>`).join('');pointsRoot.querySelectorAll('[data-auto-remove]').forEach(button=>button.onclick=guard(()=>execute([remove(button.dataset.autoRemove)],'Removed automation point')));form.elements.value.min=key==='gainDb'?-96:-1;form.elements.value.max=max;graph.onclick=guard(event=>{const rect=graph.getBoundingClientRect(),time=Math.max(0,Math.min(end,(event.clientX-rect.left)/rect.width*end)),value=Math.min(max,Math.max(min,max-(event.clientY-rect.top)/rect.height*(max-min)));execute([point({parameter:key,time:Number(time.toFixed(2)),value:Number(value.toFixed(2))})],'Added automation point');});}
 parameter.value=automationParameter;parameter.onchange=()=>{onAutomationParameter(parameter.value);draw();};draw();
 form.onsubmit=guard(e=>{e.preventDefault();execute([point({parameter:parameter.value,time:Number(form.elements.time.value),value:Number(form.elements.value.value)})],'Added automation point');});
 root.querySelector('[data-auto-clear]').onclick=guard(()=>execute([clear(parameter.value)],'Cleared automation curve'));
}
