import {z} from 'zod';
const base={id:z.string().min(1).max(100),enabled:z.boolean().default(true)};
export const effectSchema=z.discriminatedUnion('kind',[
 z.object({...base,kind:z.literal('eq'),type:z.enum(['lowpass','highpass','peaking','lowshelf','highshelf']).default('peaking'),frequency:z.number().finite().min(20).max(20000).default(1000),q:z.number().finite().min(.1).max(20).default(1),gainDb:z.number().finite().min(-24).max(24).default(0)}).strict(),
 z.object({...base,kind:z.literal('compressor'),threshold:z.number().finite().min(-80).max(0).default(-24),ratio:z.number().finite().min(1).max(20).default(4),attack:z.number().finite().min(0).max(1).default(.003),release:z.number().finite().min(.001).max(1).default(.25),knee:z.number().finite().min(0).max(40).default(15)}).strict(),
 z.object({...base,kind:z.literal('delay'),time:z.number().finite().min(.01).max(2).default(.25),feedback:z.number().finite().min(0).max(.9).default(.3),mix:z.number().finite().min(0).max(1).default(.25)}).strict(),
 z.object({...base,kind:z.literal('reverb'),decay:z.number().finite().min(.1).max(8).default(2),mix:z.number().finite().min(0).max(1).default(.2)}).strict(),
]);
export const automationSchema=z.object({id:z.string().min(1).max(100),parameter:z.enum(['gainDb','pan']),time:z.number().finite().min(0).max(86400),value:z.number().finite()}).superRefine((p,ctx)=>{const [min,max]=p.parameter==='gainDb'?[-96,12]:[-1,1];if(p.value<min||p.value>max)ctx.addIssue({code:'custom',message:'Automation value outside parameter range.'});});
export function automationValue(points,parameter,time,fallback){const ordered=points.filter(p=>p.parameter===parameter).sort((a,b)=>a.time-b.time);if(!ordered.length)return fallback;if(time<=ordered[0].time)return ordered[0].value;for(let i=1;i<ordered.length;i++){const left=ordered[i-1],right=ordered[i];if(time<=right.time)return left.value+(right.value-left.value)*(time-left.time)/(right.time-left.time);}return ordered.at(-1).value;}
export function scheduleAutomation(param,points,parameter,position,base,fallback){const transform=v=>parameter==='gainDb'?10**(v/20):v;param.setValueAtTime(transform(automationValue(points,parameter,position,fallback)),base);for(const point of points.filter(p=>p.parameter===parameter&&p.time>position).sort((a,b)=>a.time-b.time)){const t=base+point.time-position;if(parameter==='gainDb')param.exponentialRampToValueAtTime(transform(point.value),t);else param.linearRampToValueAtTime(point.value,t);}}
export function effectTail(effects=[]){return Math.min(30,effects.filter(e=>e.enabled).reduce((sum,e)=>sum+(e.kind==='reverb'?e.decay:e.kind==='delay'&&e.mix>0?e.time*(e.feedback>0?Math.ceil(Math.log(.001)/Math.log(e.feedback))+1:1):0),0));}
export function connectEffects(context,input,effects,nodes){let output=input;for(const effect of effects||[]){if(!effect.enabled)continue;
 if(effect.kind==='eq'){const filter=context.createBiquadFilter();filter.type=effect.type;filter.frequency.value=Math.min(effect.frequency,context.sampleRate/2-1);filter.Q.value=effect.q;filter.gain.value=effect.gainDb;output.connect(filter);nodes.push(filter);output=filter;}
 else if(effect.kind==='compressor'){const compressor=context.createDynamicsCompressor();for(const key of ['threshold','ratio','attack','release','knee'])compressor[key].value=effect[key];output.connect(compressor);nodes.push(compressor);output=compressor;}
 else{const dry=context.createGain(),wet=context.createGain(),sum=context.createGain();dry.gain.value=1-effect.mix;wet.gain.value=effect.mix;output.connect(dry).connect(sum);nodes.push(dry,wet,sum);
  if(effect.kind==='delay'){const delay=context.createDelay(2),feedback=context.createGain();delay.delayTime.value=effect.time;feedback.gain.value=effect.feedback;output.connect(delay);delay.connect(feedback).connect(delay);delay.connect(wet).connect(sum);nodes.push(delay,feedback);}
  else{const convolver=context.createConvolver(),length=Math.ceil(context.sampleRate*effect.decay),impulse=context.createBuffer(2,length,context.sampleRate);let seed=9173;for(let c=0;c<2;c++){const data=impulse.getChannelData(c);for(let i=0;i<length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;data[i]=(seed/2147483648-1)*(1-i/length)**3;}}convolver.buffer=impulse;output.connect(convolver).connect(wet).connect(sum);nodes.push(convolver);}
  output=sum;
 }
 }return output;}
