export const orderedMarkers=session=>[...session.markers].sort((a,b)=>a.time-b.time||a.name.localeCompare(b.name));
export function adjacentMarker(session,position,direction){const markers=orderedMarkers(session);return direction<0?markers.filter(m=>m.time<position-.000001).at(-1):markers.find(m=>m.time>position+.000001);}
export function markersView(session,position,esc,playing=false){return `<details class="daw-markers" open><summary>Markers · ${session.markers.length}</summary><div class="button-row"><button data-marker-prev ${(playing&&session.markers.length)||adjacentMarker(session,position,-1)?'':'disabled'}>Previous marker</button><button data-marker-next ${(playing&&session.markers.length)||adjacentMarker(session,position,1)?'':'disabled'}>Next marker</button></div><form data-marker-new><label>Marker name<input name="name" maxlength="200" required placeholder="Chorus, scene change…"></label><label>Time · seconds<input name="time" type="number" min="0" max="86400" step="any" value="${position}" required></label><button>Add named marker</button></form><div class="daw-marker-list">${orderedMarkers(session).map(m=>`<form data-marker-edit="${esc(m.id)}"><button type="button" data-marker-jump="${esc(m.id)}" aria-label="Go to ${esc(m.name)}">${m.time.toFixed(2)} s</button><label>Name<input name="name" maxlength="200" value="${esc(m.name)}" required></label><label>Time · seconds<input name="time" type="number" min="0" max="86400" step="any" value="${m.time}" required></label><button>Save marker</button><button type="button" data-marker-delete="${esc(m.id)}">Delete marker</button></form>`).join('')||'<p class="muted">Mark scene changes, sections, or places to revisit.</p>'}</div></details>`;}
export function bindMarkers(root,{session,position,getPosition=()=>position,seek,execute,guard}){
 const values=form=>{const name=form.elements.name.value.trim();if(!name)throw Error('Enter a marker name.');return {name,time:Number(form.elements.time.value)};};
 root.querySelector('[data-marker-new]').onsubmit=guard(e=>{e.preventDefault();execute([{op:'marker.add',values:values(e.currentTarget)}],'Added marker');});
 root.querySelectorAll('[data-marker-edit]').forEach(form=>form.onsubmit=guard(e=>{e.preventDefault();execute([{op:'marker.set',target:form.dataset.markerEdit,values:values(form)}],'Updated marker');}));
 root.querySelectorAll('[data-marker-delete]').forEach(button=>button.onclick=guard(()=>execute([{op:'marker.delete',target:button.dataset.markerDelete}],'Deleted marker')));
 root.querySelectorAll('[data-marker-jump]').forEach(button=>button.onclick=()=>{const marker=session.markers.find(m=>m.id===button.dataset.markerJump);if(marker)seek(marker.time);});
 for(const [selector,direction] of [['[data-marker-prev]',-1],['[data-marker-next]',1]])root.querySelector(selector).onclick=()=>{const marker=adjacentMarker(session,getPosition(),direction);if(marker)seek(marker.time);};
}
