import {routingView,bindRouting} from './routing.js';
import {automationView,bindAutomation} from './automation-editor.js';
function effectChainView(track,esc,master=false){return `<section><div class="daw-effect-toolbar"><h4>${esc(track.name)} · Effect chain</h4><select data-new-effect aria-label="Effect type"><option value="eq">EQ</option><option value="compressor">Compressor</option><option value="delay">Delay</option><option value="reverb">Reverb</option></select><button data-add-effect="${track.id}">Add effect</button></div>${(track.effects||[]).map((e,i)=>`<form class="daw-effect" data-effect-form="${e.id}"><div class="section-title"><strong>${i+1}. ${esc(e.kind)}</strong><label><input name="enabled" type="checkbox" ${e.enabled?'checked':''}> Enabled</label><button type="button" data-effect-up="${e.id}" data-index="${i}" ${i===0?'disabled':''}>↑</button><button type="button" data-effect-remove="${e.id}">Remove</button></div><div class="daw-effect-fields">${Object.entries(e).filter(([k])=>!['id','kind','enabled'].includes(k)).map(([key,value])=>typeof value==='number'?`<label>${esc(key)}<input type="number" step="any" name="${key}" value="${value}" required></label>`:`<label>${esc(key)}<select name="${key}">${['peaking','lowpass','highpass','lowshelf','highshelf'].map(v=>`<option ${value===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</div><button type="submit">Apply effect</button></form>`).join('')||`<p class="muted">Insert effects run in order, before the ${master?'master':'track'} fader.</p>`}</section>`;}
const masterChannel=session=>({id:session.id,name:'Master',gainDb:session.masterDb,pan:session.masterPan||0,effects:session.masterEffects||[],automation:session.masterAutomation||[]});
export function mixerView(session,selected,esc){
 const tracks=session.tracks.filter(t=>t.kind!=='video'),track=tracks.find(t=>t.id===selected)||tracks[0],masterSelected=selected===session.id,master=masterChannel(session);
 const strip=(t)=>`<div class="daw-channel ${!masterSelected&&track?.id===t.id?'selected':''}"><button data-mix-select="${t.id}">${esc(t.name)}</button><label>Volume <output>${t.gainDb.toFixed(1)} dB</output><input type="range" data-mix-gain="${t.id}" min="-60" max="12" step=".5" value="${t.gainDb}" aria-label="${esc(t.name)} volume"></label><label>Pan <output>${t.pan.toFixed(2)}</output><input type="range" data-mix-pan="${t.id}" min="-1" max="1" step=".05" value="${t.pan}" aria-label="${esc(t.name)} pan"></label><span class="muted">${t.effects?.length||0} effects · ${t.automation?.length||0} automation points</span></div>`;
 return `<section class="daw-mixer"><div class="section-title"><h3>Mixer</h3><button data-mix-select="${session.id}" aria-pressed="${masterSelected}">Master channel · ${(session.masterEffects||[]).length} effects</button><label>Master · dB<input type="number" data-master-gain min="-96" max="12" step=".5" value="${session.masterDb}"></label><label>Master · pan<input type="number" data-master-pan min="-1" max="1" step=".05" value="${session.masterPan||0}"></label></div><div class="daw-channels">${tracks.map(strip).join('')||'<p class="muted">Add audio or instrument tracks to mix.</p>'}</div>${masterSelected?`<div class="daw-mix-detail">${effectChainView(master,esc,true)}${automationView(master,esc)}</div><p class="muted daw-master-description">Processes the complete mix before master volume. Master effects also process each stem individually; compression can make the summed stems differ from the full mix. Volume and pan curves override the master controls.</p>`:track?`${routingView(session,track,esc)}<div class="daw-mix-detail">${effectChainView(track,esc)}${automationView(track,esc)}</div>`:''}</section>`;
}
export function bindMixer(root,{session,selected,select,execute,guard,duration,automationParameter='gainDb',onAutomationParameter=()=>{}}){
 root.querySelectorAll('[data-mix-select]').forEach(el=>el.onclick=()=>select(el.dataset.mixSelect));
 for(const [attr,param]of [['gain','gainDb'],['pan','pan']])root.querySelectorAll(`[data-mix-${attr}]`).forEach(input=>{input.oninput=()=>{input.parentElement.querySelector('output').textContent=input.value+(param==='gainDb'?' dB':'');};input.onchange=guard(()=>execute([{op:'track.set',target:input.dataset[attr==='gain'?'mixGain':'mixPan'],values:{[param]:Number(input.value)}}],'Updated mixer'));});
 root.querySelector('[data-master-gain]')?.addEventListener('change',guard(e=>execute([{op:'session.set',values:{masterDb:Number(e.target.value)}}],'Updated master gain')));
 root.querySelector('[data-master-pan]')?.addEventListener('change',guard(e=>execute([{op:'session.set',values:{masterPan:Number(e.target.value)}}],'Updated master pan')));
 root.querySelector('[data-add-effect]')?.addEventListener('click',guard(e=>execute([{op:'effect.add',target:e.target.dataset.addEffect,values:{kind:root.querySelector('[data-new-effect]').value}}],'Added effect')));
 root.querySelectorAll('[data-effect-form]').forEach(form=>form.onsubmit=guard(e=>{e.preventDefault();const values={};for(const input of form.querySelectorAll('[name]'))values[input.name]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;execute([{op:'effect.set',target:form.dataset.effectForm,values}],'Updated effect');}));
 root.querySelectorAll('[data-effect-remove]').forEach(button=>button.onclick=guard(()=>execute([{op:'effect.delete',target:button.dataset.effectRemove}],'Removed effect')));
 root.querySelectorAll('[data-effect-up]').forEach(button=>button.onclick=guard(()=>execute([{op:'effect.move',target:button.dataset.effectUp,values:{index:Number(button.dataset.index)-1}}],'Reordered effects')));
 const tracks=session.tracks.filter(t=>t.kind!=='video'),track=selected===session.id?masterChannel(session):tracks.find(t=>t.id===selected)||tracks[0];if(!track)return;
 if(track.id!==session.id)bindRouting(root,{track,execute,guard,duration});
 bindAutomation(root.querySelector('.daw-mix-detail > .daw-automation'),{track,execute,guard,duration,automationParameter,onAutomationParameter});
}
