import {routingView,bindRouting} from './routing.js';
import {automationValue} from './effects.js';
function effectChainView(track,esc,master=false){return `<section><div class="daw-effect-toolbar"><h4>${esc(track.name)} · Effect chain</h4><select data-new-effect aria-label="Effect type"><option value="eq">EQ</option><option value="compressor">Compressor</option><option value="delay">Delay</option><option value="reverb">Reverb</option></select><button data-add-effect="${track.id}">Add effect</button></div>${(track.effects||[]).map((e,i)=>`<form class="daw-effect" data-effect-form="${e.id}"><div class="section-title"><strong>${i+1}. ${esc(e.kind)}</strong><label><input name="enabled" type="checkbox" ${e.enabled?'checked':''}> Enabled</label><button type="button" data-effect-up="${e.id}" data-index="${i}" ${i===0?'disabled':''}>↑</button><button type="button" data-effect-remove="${e.id}">Remove</button></div><div class="daw-effect-fields">${Object.entries(e).filter(([k])=>!['id','kind','enabled'].includes(k)).map(([key,value])=>typeof value==='number'?`<label>${esc(key)}<input type="number" step="any" name="${key}" value="${value}" required></label>`:`<label>${esc(key)}<select name="${key}">${['peaking','lowpass','highpass','lowshelf','highshelf'].map(v=>`<option ${value===v?'selected':''}>${v}</option>`).join('')}</select></label>`).join('')}</div><button type="submit">Apply effect</button></form>`).join('')||`<p class="muted">Insert effects run in order, before the ${master?'master':'track'} fader.</p>`}</section>`;}
export function mixerView(session,selected,esc){
 const tracks=session.tracks.filter(t=>t.kind!=='video'),track=tracks.find(t=>t.id===selected)||tracks[0],masterSelected=selected===session.id,master={id:session.id,name:'Master',effects:session.masterEffects||[]};
 const strip=(t)=>`<div class="daw-channel ${!masterSelected&&track?.id===t.id?'selected':''}"><button data-mix-select="${t.id}">${esc(t.name)}</button><label>Volume <output>${t.gainDb.toFixed(1)} dB</output><input type="range" data-mix-gain="${t.id}" min="-60" max="12" step=".5" value="${t.gainDb}" aria-label="${esc(t.name)} volume"></label><label>Pan <output>${t.pan.toFixed(2)}</output><input type="range" data-mix-pan="${t.id}" min="-1" max="1" step=".05" value="${t.pan}" aria-label="${esc(t.name)} pan"></label><span class="muted">${t.effects?.length||0} effects · ${t.automation?.length||0} automation points</span></div>`;
 return `<section class="daw-mixer"><div class="section-title"><h3>Mixer</h3><button data-mix-select="${session.id}" aria-pressed="${masterSelected}">Master effects · ${(session.masterEffects||[]).length}</button><label>Master · dB<input type="number" data-master-gain min="-96" max="12" step=".5" value="${session.masterDb}"></label></div><div class="daw-channels">${tracks.map(strip).join('')||'<p class="muted">Add audio or instrument tracks to mix.</p>'}</div>${masterSelected?`<div class="daw-master-effects">${effectChainView(master,esc,true)}<p class="muted">Processes the complete mix before master volume. Master effects also process each stem individually; compression can make the summed stems differ from the full mix.</p></div>`:track?`${routingView(session,track,esc)}<div class="daw-mix-detail">${effectChainView(track,esc)}<section class="daw-automation"><h4>Automation · ${esc(track.name)}</h4><label>Parameter<select data-auto-parameter><option value="gainDb">Volume (dB)</option><option value="pan">Pan</option></select></label><p class="muted">Click the graph to add a point. Points interpolate smoothly and override the static fader.</p><svg data-auto-graph viewBox="0 0 600 160" preserveAspectRatio="none" aria-label="Automation curve"></svg><form data-auto-form="${track.id}"><label>Time · seconds<input type="number" name="time" min="0" step=".01" value="0" required></label><label>Value<input type="number" name="value" step=".1" value="0" required></label><button type="submit">Add point</button><button type="button" data-auto-clear="${track.id}">Clear curve</button></form><div data-auto-points></div></section></div>`:''}</section>`;
}
export function bindMixer(root,{session,selected,select,execute,guard,duration,automationParameter='gainDb',onAutomationParameter=()=>{}}){
 root.querySelectorAll('[data-mix-select]').forEach(el=>el.onclick=()=>select(el.dataset.mixSelect));
 for(const [attr,param]of [['gain','gainDb'],['pan','pan']])root.querySelectorAll(`[data-mix-${attr}]`).forEach(input=>{input.oninput=()=>{input.parentElement.querySelector('output').textContent=input.value+(param==='gainDb'?' dB':'');};input.onchange=guard(()=>execute([{op:'track.set',target:input.dataset[attr==='gain'?'mixGain':'mixPan'],values:{[param]:Number(input.value)}}],'Updated mixer'));});
 root.querySelector('[data-master-gain]')?.addEventListener('change',guard(e=>execute([{op:'session.set',values:{masterDb:Number(e.target.value)}}],'Updated master gain')));
 root.querySelector('[data-add-effect]')?.addEventListener('click',guard(e=>execute([{op:'effect.add',target:e.target.dataset.addEffect,values:{kind:root.querySelector('[data-new-effect]').value}}],'Added effect')));
 root.querySelectorAll('[data-effect-form]').forEach(form=>form.onsubmit=guard(e=>{e.preventDefault();const values={};for(const input of form.querySelectorAll('[name]'))values[input.name]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;execute([{op:'effect.set',target:form.dataset.effectForm,values}],'Updated effect');}));
 root.querySelectorAll('[data-effect-remove]').forEach(button=>button.onclick=guard(()=>execute([{op:'effect.delete',target:button.dataset.effectRemove}],'Removed effect')));
 root.querySelectorAll('[data-effect-up]').forEach(button=>button.onclick=guard(()=>execute([{op:'effect.move',target:button.dataset.effectUp,values:{index:Number(button.dataset.index)-1}}],'Reordered effects')));
 const tracks=session.tracks.filter(t=>t.kind!=='video'),track=tracks.find(t=>t.id===selected)||tracks[0],parameter=root.querySelector('[data-auto-parameter]');if(!track||!parameter)return;bindRouting(root,{track,execute,guard});
 const graph=root.querySelector('[data-auto-graph]'),pointsRoot=root.querySelector('[data-auto-points]'),form=root.querySelector('[data-auto-form]');
 function draw(){const key=parameter.value,min=key==='gainDb'?-60:-1,max=key==='gainDb'?12:1,points=(track.automation||[]).filter(p=>p.parameter===key).sort((a,b)=>a.time-b.time),end=Math.max(duration,...points.map(p=>p.time));const y=value=>160-Math.min(1,Math.max(0,(value-min)/(max-min)))*160;const drawPoints=[{time:0,value:automationValue(points,key,0,track[key])},...points,{time:end,value:automationValue(points,key,end,track[key])}];graph.innerHTML=`<path d="${drawPoints.map((p,i)=>`${i?'L':'M'} ${p.time/end*600} ${y(p.value)}`).join(' ')}"/>${points.map(p=>`<circle cx="${p.time/end*600}" cy="${y(p.value)}" r="4"/>`).join('')}<text x="8" y="16">${max}${key==='gainDb'?' dB':''}</text><text x="8" y="152">${min}</text><text x="530" y="152">${end.toFixed(1)} s</text>`;pointsRoot.innerHTML=points.map(p=>`<div><span>${p.time.toFixed(2)}s · ${p.value.toFixed(2)}</span><button data-auto-remove="${p.id}" aria-label="Remove automation point at ${p.time} seconds">Remove</button></div>`).join('');pointsRoot.querySelectorAll('[data-auto-remove]').forEach(button=>button.onclick=guard(()=>execute([{op:'automation.delete',target:button.dataset.autoRemove}],'Removed automation point')));form.elements.value.min=key==='gainDb'?-96:-1;form.elements.value.max=max;graph.onclick=guard(event=>{const rect=graph.getBoundingClientRect(),time=Math.max(0,Math.min(end,(event.clientX-rect.left)/rect.width*end)),value=Math.min(max,Math.max(min,max-(event.clientY-rect.top)/rect.height*(max-min)));execute([{op:'automation.point',target:track.id,values:{parameter:key,time:Number(time.toFixed(2)),value:Number(value.toFixed(2))}}],'Added automation point');});}
 parameter.value=automationParameter;parameter.onchange=()=>{onAutomationParameter(parameter.value);draw();};draw();
 form.onsubmit=guard(e=>{e.preventDefault();execute([{op:'automation.point',target:track.id,values:{parameter:parameter.value,time:Number(form.elements.time.value),value:Number(form.elements.value.value)}}],'Added automation point');});
 root.querySelector('[data-auto-clear]').onclick=guard(()=>execute([{op:'automation.clear',target:track.id,values:{parameter:parameter.value}}],'Cleared automation curve'));
}
