import {noteToolsView,bindNoteTools,defaultNoteTools} from './note-transform-controls.js';
import {midiEventsView,bindMidiEvents} from './midi-events.js';
export const noteName=pitch=>`${['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][pitch%12]}${Math.floor(pitch/12)-1}`;
export function pianoView(region,tempo,selected,esc,settings=defaultNoteTools){
 const beat=60/tempo,note=region.notes.find(n=>n.id===selected),width=Math.max(500,region.duration*80+28);
 return `<section class="daw-piano"><div class="section-title"><h3>Piano roll · ${esc(region.name)}</h3><div class="button-row"><button data-action="transpose">Transpose +1</button></div></div><p class="muted">Click empty space to add a note. Select a note to edit it, drag to move, or drag its right edge to resize. Timing is in beats within this region.</p>${noteToolsView(settings,Boolean(note))}<div class="daw-note-editor">${note?`<form data-note-editor="${note.id}"><label>Pitch · ${noteName(note.pitch)}<input name="pitch" type="number" min="0" max="127" step="1" value="${note.pitch}" required></label><label>Start · beats<input name="start" type="number" min="0" step="any" value="${note.start/beat}" required></label><label>Length · beats<input name="duration" type="number" min=".001" step="any" value="${note.duration/beat}" required></label><label>Velocity · 0–127<input name="velocity" type="number" min="0" max="127" step="1" value="${Math.round(note.velocity*127)}" required></label><button type="submit">Apply note</button><button type="button" data-note-delete="${note.id}">Delete note</button><button type="button" data-note-copy="${note.id}">Duplicate note</button><label>Channel<input name="channel" type="number" min="1" max="16" step="1" value="${(note.channel||0)+1}" required></label></form>`:'<p class="muted">Select a note to change its pitch, timing, length, or velocity.</p>'}</div><div class="daw-note-scroll"><div class="daw-note-grid" style="width:${width}px">${Array.from({length:128},(_,i)=>{const pitch=127-i;return `<div data-pitch="${pitch}"><span>${noteName(pitch)}</span>${region.notes.filter(n=>n.pitch===pitch).map(n=>`<button type="button" aria-label="${noteName(n.pitch)} at beat ${(n.start/beat).toFixed(2)}" aria-pressed="${n.id===selected}" title="${noteName(n.pitch)} · velocity ${Math.round(n.velocity*127)}" data-note="${n.id}" style="left:${n.start*80+28}px;width:${Math.max(8,n.duration*80)}px;opacity:${.35+.65*n.velocity}"><i data-note-resize aria-hidden="true"></i></button>`).join('')}</div>`;}).join('')}</div></div>${midiEventsView(region,tempo,esc)}</section>`;
}
export function bindPiano(root,{region,tempo,selected,select,execute,guard,settings={...defaultNoteTools}}){
 if(!region)return;bindNoteTools(root,{region,tempo,selected,settings,execute,guard});bindMidiEvents(root,{region,tempo,execute,guard});const beat=60/tempo,step=beat/4;
 root.querySelectorAll('[data-pitch]').forEach(row=>row.onclick=guard(e=>{if(e.target.closest('[data-note]'))return;const start=Math.floor(Math.max(0,e.clientX-row.getBoundingClientRect().left-28)/80/step)*step;if(start>=region.duration)return;const id=crypto.randomUUID();select(id,false);execute([{op:'note.add',target:region.id,values:{id,pitch:Number(row.dataset.pitch),start,duration:Math.min(step,region.duration-start),velocity:.8}}],'Added MIDI note');}));
 const remove=id=>execute([{op:'note.delete',target:id}],'Removed MIDI note');
 root.querySelector('[data-note-editor]')?.addEventListener('submit',guard(e=>{e.preventDefault();const f=e.currentTarget;execute([{op:'note.set',target:f.dataset.noteEditor,values:{pitch:Number(f.elements.pitch.value),start:Number(f.elements.start.value)*beat,duration:Number(f.elements.duration.value)*beat,velocity:Number(f.elements.velocity.value)/127,channel:Number(f.elements.channel.value)-1}}],'Edited MIDI note');}));
 root.querySelector('[data-note-delete]')?.addEventListener('click',guard(e=>remove(e.currentTarget.dataset.noteDelete)));
 root.querySelector('[data-note-copy]')?.addEventListener('click',guard(e=>{const n=region.notes.find(n=>n.id===e.currentTarget.dataset.noteCopy),id=crypto.randomUUID();if(n.start+n.duration*2>region.duration+.001)throw Error('There is not enough room after this note. Extend the region first.');select(id,false);execute([{op:'note.add',target:region.id,values:{...n,id,start:n.start+n.duration}}],'Duplicated MIDI note');}));
 root.querySelectorAll('[data-note]').forEach(el=>{
  el.onclick=e=>{e.stopPropagation();select(el.dataset.note);};
  el.onkeydown=guard(e=>{if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove(el.dataset.note);}});
  el.onpointerdown=e=>{if(e.button!==0)return;e.stopPropagation();const n=region.notes.find(n=>n.id===el.dataset.note),x=e.clientX,y=e.clientY,resize=Boolean(e.target.closest('[data-note-resize]'));let moved=false,values=null;el.setPointerCapture(e.pointerId);
   el.onpointermove=event=>{const dx=event.clientX-x,dy=event.clientY-y;if(!moved&&Math.abs(dx)+Math.abs(dy)<4)return;moved=true;const shift=Math.round(dx/80/step)*step;values=resize?{duration:Math.max(Math.min(step,region.duration-n.start),Math.min(region.duration-n.start,n.duration+shift))}:{start:Math.max(0,Math.min(region.duration-n.duration,n.start+shift)),pitch:Math.max(0,Math.min(127,n.pitch-Math.round(dy/16)))};if(resize)el.style.width=`${Math.max(8,values.duration*80)}px`;else{el.style.left=`${values.start*80+28}px`;el.style.transform=`translateY(${(n.pitch-values.pitch)*16}px)`;}};
   const cleanup=()=>{el.onpointermove=null;el.onpointerup=null;el.onpointercancel=null;};
   el.onpointercancel=()=>{cleanup();select(n.id);};el.onpointerup=guard(event=>{cleanup();el.releasePointerCapture(event.pointerId);if(moved&&values){select(n.id,false);execute([{op:'note.set',target:n.id,values}],resize?'Resized MIDI note':'Moved MIDI note');}else select(n.id);});
  };
 });
}
